apiVersion: kctrl.carvel.dev/v1alpha1
kind: PackageBuild
metadata:
  creationTimestamp: null
  name: cert-manager.thomasvitale.dev
spec:
  release:
  - resource: {}
  template:
    spec:
      app:
        spec:
          deploy:
          - kapp:
              rawOptions:
              - --wait-timeout=5m
              - --kube-api-qps=50
              - --kube-api-burst=100
          template:
          - ytt:
              paths:
              - config
          - kbld: {}
      export:
      - imgpkgBundle:
          image: ghcr.io/thomasvitale/cert-manager-package-demo
          useKbldImagesLock: true
        includePaths:
        - config
