#@ load("@ytt:data", "data")
#@ load("@ytt:overlay", "overlay")

#@ def argo_service():
kind: Service
metadata:
  name: argocd-server
#@ end

#@overlay/match by=overlay.subset(argo_service())
---
spec:
  #@overlay/match missing_ok=True
  type: #@ data.values.service_type
