apiVersion: vendir.k14s.io/v1alpha1
kind: Config

directories:
- contents:
  - git:
      ref: v2.7.7
      url: https://github.com/argoproj/argo-cd
    includePaths:
    - manifests/install.yaml
    newRootPath: manifests
    path: .
  path: config/upstream
