apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  creationTimestamp: null
  name: platform.thomasvitale.dev.0.0.0
spec:
  refName: platform.thomasvitale.dev
  releasedAt: null
  template:
    spec:
      deploy:
      - kapp: {}
      fetch:
      - git: {}
      template:
      - ytt:
          paths:
          - config
      - kbld: {}
  valuesSchema:
    openAPIv3: null
  version: 0.0.0

---
apiVersion: data.packaging.carvel.dev/v1alpha1
kind: PackageMetadata
metadata:
  creationTimestamp: null
  name: platform.thomasvitale.dev
spec:
  displayName: platform
  longDescription: platform.thomasvitale.dev
  shortDescription: platform.thomasvitale.dev

---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  annotations:
    kctrl.carvel.dev/local-fetch-0: .
  creationTimestamp: null
  name: platform
spec:
  packageRef:
    refName: platform.thomasvitale.dev
    versionSelection:
      constraints: 0.0.0
  serviceAccountName: platform-sa
status:
  conditions: null
  friendlyDescription: ""
  observedGeneration: 0
