apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: argo-cd
  namespace: platform
spec:
  packageRef:
    refName: argo-cd.thomasvitale.dev
    versionSelection:
      constraints: 2.9.3
  serviceAccountName: kadras-install-sa
